### ISSUE TITLE
&override property behavior

### ISSUE THREAD

**Issue by cmccloud** [hlissner/emacs-doom-themes#203]
Faces set with the &override property seem to persist through changes to another doom-theme, unless the newly switched to theme also defines that face using &override.

Recipe:
Enable show-paren-mode
Enable doom-one-light theme
Take note of the paren-face-match (doom-one-light defers to doom-themes-common)
Disable doom-one-light theme
Enable doom-nova theme (or any other theme which defines paren-match using override, such as doom-nord-light or doom-nord)
Take note of the paren-face-match
Disable doom-nova theme
Enable doom-one-light theme

paren-face-match will be unchanged from doom-nova, and this will persist across  any other doom-themes that do not use &override to set paren-match-face. 

In trying to debug this I found that the value of `(doom-themes-common-faces)` is also being changed. I haven't looked enough at the macros to see if it's intended behavior, but I honestly cant imagine that it is. Here is the output of a new emacs session, I've cleaned up some of the pretty printing results for brevity:

```
(disable-theme 'spacemacs-dark)
(load-theme 'doom-one-light)
(pp (doom-themes-common-faces))
"(
 ....
 (paren-face-match :foreground red :background base0 :weight 'ultra-bold)
 (paren-face-mismatch :foreground base0 :background red :weight 'ultra-bold)
 (paren-face-no-match :inherit 'paren-face-mismatch :weight 'ultra-bold)
 (paren-face :foreground comments)
 ....
)
"
(disable-theme 'doom-one-light)
(load-theme 'doom-nova)
(pp (doom-themes-common-faces))
"(
 ....
 (paren-face-match :foreground red :background
                   (doom-darken violet 0.4)
                   :weight 'ultra-bold)
 (paren-face-mismatch :foreground
                      (doom-darken red 0.4)
                      :background cyan :weight 'ultra-bold)
 (paren-face-no-match :inherit 'paren-face-mismatch :weight 'ultra-bold)
 (paren-face :foreground comments)
 ....
 )
"
(disable-theme 'doom-nova)
(load-theme 'doom-one-light)
(pp (doom-themes-common-faces))
"(
 ....
 (paren-face-match :foreground red :background
                   (doom-darken violet 0.4)
                   :weight 'ultra-bold)
 (paren-face-mismatch :foreground
                      (doom-darken red 0.4)
                      :background cyan :weight 'ultra-bold)
 (paren-face-no-match :inherit 'paren-face-mismatch :weight 'ultra-bold)
 (paren-face :foreground comments)
 ....
)
"
```

**Comment by cmccloud** [comment]
As an aside, this is likely the root cause of #166, as reevaluating the doom-themes-common-faces defun restores expected behavior in both cases.

Recipe:
(load-theme 'doom-one)
(disable-theme 'doom-one)
(load-theme 'doom-nord)
(disable-theme 'doom-nord)
(load- theme 'doom-one) //=> symbols value as variable is void: region-fg
(load-file "/path/to/doom-themes-common.el") ;; C-x C-e on doom-themes-common-faces works too
(load-theme 'doom-one) // => works fine

**Comment by hlissner** [comment]
Thank you for looking into this. It's given me exactly the lead I needed! I'll look into a solution soon.

**Comment by cmccloud** [comment]
I will be extremely curious to see what the cause is, godspeed =)

**Comment by hlissner** [comment]
Alright, as of 37ff8c8 this should be resolved.

The cause of this is quite simple. I did a shallow copy of `doom-themes-common-faces` when I meant to be deep-copying it. This means that, if I copied it to `x`, I don't have a copy of the entire list, I only have a copy of the list _structure_; `x`'s elements would be references to the original faces in `doom-themes-common-faces`. So when I mutated them in `x`, it would mutate the original. 

Compound this each time a theme was loaded and `doom-themes-common-faces` will eventually contain specs that are incompatible with other themes, causing errors.

The fix was simple: don't do `(copy-sequence doom-themes-common-faces)`, do `(mapcar #'copy-sequence doom-themes-common-faces)`.

However, while debugging this I noticed another glaring issue to do with inheritance chains not cascading properly. e.g. if A &inherit'ed B in `doom-themes-common-faces` and B was redefined in the theme, A would reflect the old B instead of the new one. This prompted the larger rewrite.

**Comment by cmccloud** [comment]
I didn't realize this was possible, honestly. Had doom-themes-common-faces been a variable, it would have made perfect sense that it was being mutated, but since it was a function, and what was being passed was a function call, I thought the internal structure should have been protected.

**Comment by hlissner** [comment]
You're exactly right, but this is a trick of lexically bound closures and the byte-compiler being a little too clever, optimizing out calls to the function and referring to its constant return value with the same byte opcode everywhere where it is used. The effect is the same as if I had used a variable!

I hadn't anticipated that when I first made them functions.

**Comment by cmccloud** [comment]
Really appreciate the explanation.
