### ISSUE TITLE
Doom-one theme: face for the current line drastically changes color of text

### ISSUE THREAD

**Issue by rieje** [hlissner/emacs-doom-themes#204]
Disclaimer: I'm a complete noob. 

Better to explain with pictures:

[With current line on `persp-face-lighter-buffer-not-in-persp`](https://ptpb.pw/APS6gnB9X7h3IdoH4vhazuaYGs4O.png) and [without that line focused](https://ptpb.pw/AAB-FmLMKAKNtMAskzKpp0zUee9K.png).

I was really confused as I was wondering why the result of `persp-face-lighter-buffer-not-in-persp` does not show the actual face that it's supposed to show until I realized that the face used by `doom-one`'s current line changed it drastically.

Is this expected behavior? What is the best way to handle this?

Much appreciated.

**Comment by hlissner** [comment]
Unfortunately, this is an unavoidable limitation of Emacs. `hl-line` uses overlays to highlight the current line and `list-faces-display` uses text-properties. Overlays always override text properties. Since both hl-line and `persp-face-light-buffer-not-in-persp` define a background color, hl-line's will always win.

The only way to handle this would be to rewrite hl-line to use text-properties or list-face-display to use overlays, but it wouldn't fix the issue anywhere else (like with rainbow-mode).
