### ISSUE TITLE
Python looks dull in City Lights

### ISSUE THREAD

**Issue by r-darwish** [hlissner/emacs-doom-themes#207]
![citylights](https://user-images.githubusercontent.com/1383193/43141578-edea613e-8f5e-11e8-90c9-378954c621ad.png)
![one](https://user-images.githubusercontent.com/1383193/43141579-ee091d18-8f5e-11e8-8fb8-d15a76ba091b.png)

I'm not sure if this duplicates #202.

Variables in City Lights don't seem to have a color to distict them from the rest of the code, which makes Python appear duller than in One

**Comment by hlissner** [comment]
This appears to be deliberate of the city-lights colorscheme (see http://citylights.xyz/), as such I'm unwilling to change it, unless I am mistaken.

However, it can easily be customized by running any of these after you've loaded the doom-city-lights theme:

```lisp
;; run this after you've loaded doom-city-lights
(set-face-foreground 'font-lock-variable-name-face (doom-color 'green))

;; ...or if we want to change more than just it's color:
(set-face-attribute 'font-lock-variable-name-face nil :foreground (doom-color 'green) :slant 'italic :weight 'bold)
```

Hope that helps!

**Comment by ema2159** [comment]
Mine looks even worse, I don't get the purple color in the functions nor the green color in the strings, why is this?
![city_lights](https://user-images.githubusercontent.com/17773218/53844897-2ff7c000-3f75-11e9-9f60-f02879950f32.png)

**Comment by hlissner** [comment]
Unfortunately, it is virtually impossible to get colorschemes to look as consistent as they do in other editors without some hefty work. There aren't enough "base" faces to work with, and major mode devs can apply them to whatever they want, as much or as little as they like. So fixing this issue is out of scope for this project.

If I recolor them to match the python screenshots on http://citylights.xyz, then it will be at the expense of every other major mode. Perhaps you can use `face-remap` to buffer-locally color faces differently,add your own font-lock keywords, or overwrite the ones these modes use.

The best we can do is pressure major mode developers to use their own custom faces that inherit from the base ones, like js2-mode and enh-ruby-mode does (to some extent), then we'd have much, much more control over the situation.

**Comment by ema2159** [comment]
Such a shame! Thanks anyway!

**Comment by ema2159** [comment]
Just if somebody needs this in the future, I added this in my config to improve python-mode dull default syntax highlight:
```emacs-lisp
;; Improve python-mode syntax highlighting
(font-lock-add-keywords 'python-mode
  '(("-?\\b[0-9]+\\.?" . font-lock-constant-face)
    ("[\.\,\;\:\*\|\&\!\(\)\{\}\=\$\<\>\'\#\%\-\+\@]\\|\\]\\|\\[" . font-lock-keyword-face)
    ("\\([A-Za-z][A-Za-z0-9_]*\\)[ \t\n]*\\((.*)\\)"
     (1 font-lock-function-name-face))))
```
This is a comparison between the default and the enhanced syntax highlighting with those lines in the config
![wo_mod](https://user-images.githubusercontent.com/17773218/54064045-ea3e3000-41de-11e9-990e-fe5969fc4992.png) ![with_mod](https://user-images.githubusercontent.com/17773218/54064043-e4e0e580-41de-11e9-96b1-447f4f82a0d2.png)
Is not much, but maybe it helps somebody
