### ISSUE TITLE
[QUESTION] doom-themes-set-faces

### ISSUE THREAD

**Issue by lambdadelta34** [hlissner/emacs-doom-themes#246]
Hello, my doom-dracula theme is very dark in terminal emacs, so i tried to tweak some foreground colours in faces, but  i can't figure out how to use `doom-themes-set-faces` in my init file.

**Comment by hlissner** [comment]
My apologies for the late response.`doom-themes-set-faces` is supposed to let you modify your theme using the same syntax that the themes in this package use, _however, it is currently broken and I haven't had time to look into it.

As an alternative, your best bet is to use Emacs' `set-face-*` functions _after_ you've loaded a theme. This package also exposes some functions that could help, like `doom-color`, `doom-lighten`, and `doom-darken`, e.g.

```lisp
(require 'doom-themes)
(load-theme 'doom-one t)
(set-face-background 'default (doom-color 'red))
(set-face-foreground 'error (doom-lighten 'red 0.25))
(set-face-attribute 'success nil :foreground (doom-darken 'green 0.5))
```

Hope that helps!

**Comment by mattsawyer77** [comment]
Hi @hlissner. I'm trying out your suggested workaround above (I noticed peacock doesn't really style the `variables` or `type` in the theme). But the following resulted in `(error Invalid face variables)` for me:

```elisp
(require 'doom-themes)
(load-theme 'doom-peacock t)
(set-face-background 'variables (doom-color 'cyan))
```

**Comment by lambdadelta34** [comment]
Thank you @hlissner, though I'm not using terminal emacs anymore 😃 .

**Comment by hlissner** [comment]
@mattsawyer77 Sorry for the late response; I only noticed your reply just now. `variables` is not a face that exists. You might've wanted `font-lock-variable-name-face` instead. Some major modes have defined their own (or extra) faces for variables, e.g. like js2-mode's `js2-external-variable` face. You'd have to look those up. Perhaps `M-x describe-face` can help you look up faces. Otherwise it's possible to open a mode's library (e.g. `M-x find-library RET js2-mode`) and search for `defface` declarations.

@lambdadelta34 Happy to help! In that case I'll consider this issue resolved.

**Comment by mattsawyer77** [comment]
thanks @hlissner!

**Comment by angrybacon** [comment]
Is `doom-themes-set-faces` still considered broken?

``` el
(doom-themes-set-faces 'doom-one
  (font-lock-comment-face :foreground magenta))
```
Yields

```text
Debugger entered--Lisp error: (void-function font-lock-comment-face)
  (font-lock-comment-face :foreground magenta)
  (doom-themes-set-faces 'doom-one (font-lock-comment-face :foreground magenta))
  eval-region(8217 8302)  ; Reading at buffer position 8302
  me/eval-region-and-kill-mark(8217 8302)
  funcall-interactively(me/eval-region-and-kill-mark 8217 8302)
  call-interactively(me/eval-region-and-kill-mark nil nil)
  command-execute(me/eval-region-and-kill-mark)
```
