### ISSUE TITLE
Flycheck errors are unreadable (white text on yellow bg)

### ISSUE THREAD

**Issue by kevinji** [hlissner/emacs-doom-themes#250]
I'm not entirely sure whether this is an issue with doom-theme, tuareg-mode, or flycheck, but the popup from flycheck is rendering in white text on a yellow background. I've attached a screenshot demonstrating the issue.

<img width="937" alt="screenshot 2018-12-15 15 35 54" src="https://user-images.githubusercontent.com/1146876/50047229-6eb96080-007f-11e9-85ed-2b93fff29db6.png">

Is there a good way to fix this, or at least figure out the cause of the issue?

**Comment by mc10** [comment]
Yep, I'm using macOS Mojave (10.14) and these tooltips are being generated by [flycheck-pos-tip](https://github.com/flycheck/flycheck-pos-tip). It seems like the default font color is black; would it be possible to reset the font color to black instead of white, as a temporary fix? Also, how could I test theming the background of the tooltip?

**Comment by hlissner** [comment]
Ah, so sorry for the tremendously late response. If you're still experiencing this, you could try this:

```lisp
(set-face-foreground 'tooltip "#000000")
```

This must be placed after you've loaded the theme.

**Comment by hlissner** [comment]
Feel free to follow up here if you have more to ask, but I will consider this resolved and close this thread.
