### ISSUE TITLE
Improve file type icons in treemacs (solution provided)

### ISSUE THREAD

**Issue by memeplex** [hlissner/emacs-doom-themes#262]
Currently all code/text file types share the same icon. You can do better changing the code in doom-themes-treemacs.el to something like the following snippet (adding more extensions and text types, of course, but I'm sure you get the idea):

```elisp
  (dolist (ext '("py" "c"))
    (treemacs-define-custom-icon
     (catch 'found
       (dolist (item all-the-icons-icon-alist)
         (when (string-match-p (car item) (concat "." ext))
           (throw 'found (apply (cdr item)))))
       (all-the-icons-octicon "file-code"))
       ext)))
```

**Comment by memeplex** [comment]
Notice the code is `O(N x M)` but I don't think that could be a problem.

**Comment by hlissner** [comment]
This was intentional. I didn't want per-filetype icons; I was taking after the simplicity of Atom's sidebar:

![image](https://user-images.githubusercontent.com/510883/52921169-41d53400-32e2-11e9-8761-3bc7f1119e38.png)

If you want per-filetype icons (and still want to keep the modifications offered by doom-themes-treemacs), you can turn off only the custom icons with `(setq doom-treemacs-use-generic-icons nil)` then apply your own

**Comment by memeplex** [comment]
Ok if that's intentional, thanks!
