### ISSUE TITLE
New dark+ color theme

### ISSUE THREAD

**Issue by seagle0128** [hlissner/emacs-doom-themes#279]
Is it possible to add the very nice new dark+ theme from VSCode?

Reference: 
https://github.com/Microsoft/vscode/tree/master/extensions/theme-defaults/themes
https://github.com/dunstontc/darkplus-emacs

![image](https://user-images.githubusercontent.com/140797/60413277-dfccf980-9c06-11e9-9e5d-894a97607d2d.png)

**Comment by ema2159** [comment]
Hi mr. Zhang. I can can implement this but just out of curiosity, isn't this theme similar to the `doom-one` theme?

**Comment by seagle0128** [comment]
Thank you for following up this, @ema2159 !

True, the `dark+` is similar as `doom-one`, but different. The colors are warmer and more match with some DE. I think it's a good option for the users.

**Comment by ema2159** [comment]
I'm currently really active implementing stuff, so you can expect this soon. Yo also can submit a PR using the doom-one-theme.el file as a template and following the official color pallette from the theme

**Comment by seagle0128** [comment]
FYI
https://github.com/ianpan870102/vscode-dark-plus-emacs-theme

**Comment by ema2159** [comment]
Nice! I can use that

**Comment by ianpan870102** [comment]
@ema2159 I'd be grateful if you could port this to doom-themes. Take your time!

**Comment by ema2159** [comment]
Well, let's do it

**Comment by ema2159** [comment]
Almost there! I just need to tweak the modeline, tabs, maybe treemacs, and then I'll merge it. Then, I need that you test the hell out of it to find any contrast problems, differences from the original theme etc.

![DeepinScreenshot_dde-desktop_20200120005915](https://user-images.githubusercontent.com/17773218/72705139-373da300-3b20-11ea-98fc-aebf1aed5787.png)

**Comment by seagle0128** [comment]
Cool! I prefer colorful mode-line, which is different the original theme. Thanks!

**Comment by ema2159** [comment]
@seagle0128 sorry for my bad screenshot-taking skills 😅, yes the modeline's is blue like in the original, it's just that in the screenshot the focus is on Treemacs.

**Comment by seagle0128** [comment]
> @seagle0128 sorry for my bad screenshot-taking skills 😅, yes the modeline's is blue like in the original, it's just that in the screenshot the focus is on Treemacs.

Oh, never mind! I just want to use my own `doom-modeline` in this beautiful theme :smile:

**Comment by ema2159** [comment]
@seagle0128 @ianpan870102 done! I really put lot of love in this one. The only thing I don't quite like is the Dashboard's page-break-lines and init info because the face is harcoded (by me :sweat_smile:) to the comment's color. I would rather put it blue, but that needs to be changed in the dashboard repo. Please tell me what you think! I really like the way it looks.

**Comment by seagle0128** [comment]
Thanks, @ema2159. It looks great! I love it.

I'm fine with the color of `page-break-lines`. I can customize it if I don't like it.

I got some minor issues with `doom-modeline`. It makes the mode-line "lose" the most of the colors.
![image](https://user-images.githubusercontent.com/140797/72819396-26b83480-3ca8-11ea-83b7-9bd0d518dbd1.png)

It should like this:
![image](https://user-images.githubusercontent.com/140797/72819492-536c4c00-3ca8-11ea-917d-bcd6b5fac870.png)

**Comment by ema2159** [comment]
That's a design choice given that the original modeline from VS Code looks like that i.e.:
![image](https://user-images.githubusercontent.com/17773218/72820017-dd2e0200-3c33-11ea-92c1-3dc643e20030.png)

The problem is that the color of the modeline is too bright to have a decent contrast with the colors. What do you propose?

**Comment by seagle0128** [comment]
Okay. But some icons have colors, but others have not. It looks wired.

**Comment by ema2159** [comment]
That's because there's some faces I missed that I need o set explicitly, I'll change them so they look better. The only thing that I can't make look good is the mode's icon, which one has to configure in doom-modeline directly.

Well, I like more the blue modeline because it looks smoother and integrates better with the ui, but a custom to switch between both colors is also an option!

**Comment by seagle0128** [comment]
Great! I've already integrated dark+ theme into [Centaur Emacs](https://github.com/seagle0128/.emacs.d).

You are right, `doom-modeline` provides an option to control buffer icons.

**Comment by ema2159** [comment]
Awesome!!! I really enjoy working on this.

**Comment by ema2159** [comment]
Done, now the mode line is violet by default and the mode line's color can be set to blue by changing the `doom-dark+-blue-modeline` custom variable.

The mode line elements' colors were all set to white except by a few exceptions (lsp warning and error, evil non-normal states among others). Please report any other problems you find!
