### ISSUE TITLE
Can't install from MELPA Stable: package ‘font-lock+-0’ is unavailable

### ISSUE THREAD

**Issue by mpolden** [hlissner/emacs-doom-themes#28]
When I try to install `doom-themes` from MELPA stable I get an error:

```
M-x package-install RET doom-themes RET
Package ‘font-lock+-0’ is unavailable
```

**Comment by ignacy** [comment]
👍

**Comment by hlissner** [comment]
Peculiar. I didn't even know my package depended on `font-lock+`! Very well, I added it to the dependencies. Let me know if that fixes your problem!

**Comment by martinp** [comment]
@hlissner I think the problem is that `font-lock+` isn't available on stable.

**Comment by hlissner** [comment]
It looks like this issue is coming from all-the-icons, which requires `font-lock+`. They have [an issue open for this](https://github.com/domtronn/all-the-icons.el/issues/32).

So there is nothing I can do about this. I ([and the creators of MELPA, it would seem](https://github.com/melpa/melpa#melpa-stable)) suggest that you don't use MELPA Stable.

I will keep the issue open for posterity.

**Comment by Avaholic92** [comment]
This is still an issue attempting to install in 25.2 from melpa (on Win10... dont judge me I have to use Windows at work)

**Comment by a13** [comment]
There's a "mirror" of font-lock+ on github now, so one can use quelpa to install it (or even use :url fetcher to load it from Emacswiki)

```
(use-package font-lock+
  :ensure t
  :quelpa
  (font-lock+ :repo "emacsmirror/font-lock-plus" :fetcher github))
```
