### ISSUE TITLE
Treemacs got updated

### ISSUE THREAD

**Issue by ema2159** [hlissner/emacs-doom-themes#288]
Treemacs just got updated so I think the `doom-themes-treemacs-config` function doesn't work anymore

**Comment by andreyorst** [comment]
It partly works, e.g. basic text file icons got changed, but directories and filetype icons not.

**Comment by kreisys** [comment]
Yeah looks like https://github.com/Alexander-Miller/treemacs/commit/4bd9421b56938d21ee347f6e5c59d1cb00ce23e9 is the culprit since it changes the names of the symbols representing a bunch of icons.

**Comment by andreyorst** [comment]
It seems taht treemacs now supports themes, so maybe these parts of treemacs configurations from emacs-doom-themes could be externalized into proper doom-treemacs-theme.

**Comment by kreisys** [comment]
After taking a closer look it doesn't look like symbol names are the culprit here... I tried to fork and change them but 1) it didn't make a difference and 2) the only symbol names that changed seem to be related to open/closed directories. I also tried to just pin an older commit which didn't seem to work. Neotree is different enough to disrupt my workflow quite substantially. Does anyone have a workaround? :|

**Comment by Alexander-Miller** [comment]
> It seems taht treemacs now supports themes, so maybe these parts of treemacs configurations from emacs-doom-themes could be externalized into proper doom-treemacs-theme.

Pretty much the reason I wrote the whole thing.. That and making the code a whole lot simpler.

I have just pushed a change that lets you create a theme with non-file icons. Based on what @andreyorst showed in https://github.com/Alexander-Miller/treemacs/issues/465 a doom theme for treemacs would be defined and used like this:

```Elisp
(treemacs-create-theme "DOOM One"
  :config
  (progn
    (treemacs-create-icon
     :icon (concat " " (all-the-icons-octicon
                        "file-directory"
                        :v-adjust 0
                        :face '(:inherit font-lock-doc-face :slant normal))
                   " ")
     :extensions (root))
    (treemacs-create-icon
     :icon (concat (all-the-icons-octicon
                    "chevron-down"
                    :height 0.75
                    :face '(:inherit font-lock-doc-face :slant normal))
                   " "
                   (all-the-icons-octicon
                    "file-directory"
                    :v-adjust 0
                    :face '(:inherit font-lock-doc-face :slant normal))
                   " ")
     :extensions (dir-closed))
    (treemacs-create-icon
     :icon (concat (all-the-icons-octicon
                    "chevron-right"
                    :height 0.9
                    :face '(:inherit font-lock-doc-face :slant normal))
                   " "
                   (all-the-icons-octicon
                    "file-directory"
                    :v-adjust 0
                    :face '(:inherit font-lock-doc-face :slant normal))
                   " ")
     :extensions (dir-open))
    (treemacs-create-icon
     :icon (concat "  " (all-the-icons-octicon "file-code" :v-adjust 0))
     :extensions ("yaml" "yml" "json" "xml" "toml" "cson" "ini"
                  "tpl" "erb" "mustache" "twig" "ejs" "mk" "haml" "pug" "jade"))))

(treemacs-load-theme "DOOM One")
```

It's not yet all documented, and there's some magic parts like `:extensions (root)`, so for now you'll need to look up that stuff in https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-icons.el#L142.

**Comment by Majenful** [comment]
Maybe you can get inspiration from 
https://github.com/ogdenwebb/emacs-kaolin-themes/commit/e12ffc4e0ee19482ae94b9a82c84c0aae55bef08

**Comment by kreisys** [comment]
> Maybe you can get inspiration from
> [ogdenwebb/emacs-kaolin-themes@e12ffc4](https://github.com/ogdenwebb/emacs-kaolin-themes/commit/e12ffc4e0ee19482ae94b9a82c84c0aae55bef08)

This is actually a pretty solid workaround. I ended up copying the linked file verbatim to my as `~/.doom.d/+treemacs-tmp-fix.el`, then in my `~/.doom.d/config.el` I added:

```elisp
(after! doom-themes
  (defun doom-themes-treemacs-config ()
    (load! "+treemacs-tmp-fix.el")))
```

It's arguably nicer than the original. If you like more icons 🙃
Anyways that's my 2 cents. Hope it brightens someone's day as it did mine 😅

**Comment by andreyorst** [comment]
I've ended up stripping away doom-themes configuration of treemacs away and just created a theme that looks how I like. [Here's](https://github.com/andreyorst/dotfiles/blob/7535bdd24f5f0a8d0a9e3a48e02d4a3d091731b7/.emacs.d/init.el#L262-L499) my treemacs, config. I created the theme right inside the `use-package` macro, and it looks like this:

![image](https://user-images.githubusercontent.com/19470159/60354613-466ad100-99d5-11e9-81c0-caa44321e1d1.png)

I did take the [`doom--treemacs-variable-pitch-labels`](https://github.com/hlissner/emacs-doom-themes/blob/55c49c8fd6152ebb748e75197c064b6ae7db1a57/doom-themes-treemacs.el#L36-L53) function though, because without it the spacings of the letters are bit off.

**Comment by hlissner** [comment]
As of 06a6292, it should be fixed, though may need additional tweaking. In any case, I'll consider this resolved, but let me know if that isn't the case and I will reopen it. Thank you for bringing it to my attention and for all the help and resources; it made fixing it a whole lot faster!

**Comment by Alexander-Miller** [comment]
FYI I have now included [documentation](https://github.com/Alexander-Miller/treemacs#theme-support) for the theme api.
