### ISSUE TITLE
Solarized dark theme

### ISSUE THREAD

**Issue by ema2159** [hlissner/emacs-doom-themes#290]
Would you be open to implement the Solarized dark theme (or accept a PR)?

**Comment by ema2159** [comment]
Hello Mr. @hlissner, I just wanted to let you know I'm working on it. It currently looks like this:
![DeepinScreenshot_select-area_20190714185514](https://user-images.githubusercontent.com/17773218/61191543-1f64fe00-a669-11e9-95c3-1b934ce58948.png)



I used doom-city-lights as a template because it's a similar color pallete and I've been using VS Code as reference as well as the official theme page (https://ethanschoonover.com/solarized/), tweaking the colors until I'm able to reach a point in which it looks as similar as the original as possible. I'll be glad to hear your feedback! This is one of the most used themes overall and I consider `doom-themes` to be the best theme packages for Emacs so I think this will be a great addition. I need to finish tweaking the terminal colors but I think it's looking good, what do you think?

**Comment by hlissner** [comment]
Hi there! Sorry for the late response. I think this looks great! However, I must refuse merging this: I am currently rewriting doom-themes and its API, and intend to split the package into multiple packages:

+ One for the theme API (not sure yet if it will be doom-themes-core or if I'll come up with a new name for it)
+ This repo will be reworked to only contain this package's flagship themes: `doom-one`, `doom-one-light` and `doom-one-vibrant`
+ And two plugins, one for our neotree theme and the other for treemacs

All our other themes will either be moved into their own individual packages (and submitted to melpa separately) or to https://github.com/Emiller88/emacs-doom-community-themes. I would encourage you to do one of these things. In fact, if you are willing to maintain the solarized theme, I'd be happy to give it to you if you'd like to createa doom-solarized pack or similar.

In any case, the rewrite will be done within the next two weeks.

**Comment by ema2159** [comment]
Hi Henrik! I am willing to maintain my implementation of Solarized, however, may I ask why are you going to separate the package? I think the greatest thing about this plugin is that instead of having a lot of theme packages hanging around in MELPA the user has access to a lot of nice themes in a single package. In fact that's why it has become my favourite theme package, so I'm really intrigued about why you've made this decision. 

As a matter of fact I'm implementing my own multi theme package using the same core porting multiple popular themes into one package using the same file structure.

By the way, I've seen that @Emiller88 has taken my Solarized implementation so how should I proceed?

**Comment by hlissner** [comment]
After some thought and discussion, I've come around to keeping the themes together -- well, only for the themes that I am certain I can maintain on my own or with help.

I'll still split the api and extensions out into their own thing, but I want to be more selective about the themes I allow into this megapack.

I had three concerns going into this decision:

1. The project's scope is too beg to handle on my own: many of its current themes I have never used and are no longer maintained by their original authors, but I still get bug reports for. That's before the requests and PRs.

2. I'm a bit bothered by the duplication in the emacs ecosystem. Counting this one, there are 3 solarized theme packages, two nord themes, two nova themes, and so on. It doesn't need to be this way. I'd rather encourage people to use the new doom api to improve those ones, rather than bring a copy into this package.

3. The API is poorly written, terribly inefficient and undocumented, first written when I knew little about Emacs and elisp. The compile-time magic involved with every theme makes `M-x package-install RET doom-themes` dreadfully slow, and makes it a pain point for any doom theme author aspirant who pulls it in as a base. I can't imagine how it'd be for folks using their own local, un-byte-compiled doom themes. 

----

In any case, the rewrite addresses many of these issues, so I think I can tolerate the workload of maintaining a megapack.

**Comment by hlissner** [comment]
> By the way, I've seen that @Emiller88 has taken my Solarized implementation so how should I proceed?

Ah, I forgot to respond to this. I'll merge #303 -- solarized is one theme I'd like in this pack. I realize this confuses things, but I'll remove it from the community pack shortly.

**Comment by ema2159** [comment]
Nice nice, just one thing, are you ok with the org appearance for that theme? I changed it in my local  but I'm not sure if you'd like me to upload those changes
