### ISSUE TITLE
Org-crypt will overwrite user settings in ~/.doom.d/config.el

### ISSUE THREAD

**Issue by lanrete** [hlissner/emacs-doom-themes#297]
I've been using tag "project" to mark my project in org agenda view, and therefore have below line in my `~/.doom.d/config.el`:
`(setq org-tags-exclude-from-inheritance) '("project")`

This works at the beginning, but after certain operations on the org file, including: setting tags using org-set-tags-command and org-capture, the settings seems to be overwrite to "crypt".

I did some research and found that there is a code hook [here](https://github.com/hlissner/doom-emacs/blob/096a3b96cccee3f555a55555151bce6c04d09492/modules/lang/org/config.el#L871)  in `~/.emacs.d/modules/lang/org/config.el` where it directly set the `org-tags-exclude-from-inheritance` to `'("crypt")`. I think this might be what went wrong here.

There are two potential fix for this problem. 

1. I can make some changes to my own config, maybe adding another code hook to overwrite the `'("crypt")` value once again.
2. We can open a PR for this to have the built-in code hook fixed to append `'("crypt")` to the end of the list instead of setting the value directly.

Please let me know your thought on this

**Comment by hlissner** [comment]
I think you posted this in the wrong issue tracker (it should be in [doom-emacs's issue tracker](https://github.com/hlissner/doom-emacs)), but I'll answer it here:

Since (almost) all packages in Doom Emacs are lazy loaded, it is imperative you wrap your configuration of packages in an `(after! PACKAGE ...)` block. In your case:

```elisp
(after! org-crapt
  (setq org-tags-exclude-from-inheritance '("project")))
```

The only exception to this rule are variables representing file paths (like `org-directory`).

In any case, I'll change it to use `add-to-list` rather than `setq`. Note that this will accommodate your use case, but is the purpose of the change. Rather, it's so that Doom doesn't mask the default value of `org-tags-exclude-from-inheritance`. It is `nil`, right now, but just in case it changes in the future.

> (setq org-tags-exclude-from-inheritance) '("project")

I think this was a typo, but just to be sure, there is a premature closing parenthesis after `org-tags-exclude-from-inheritance` that would prevent it from being set properly.

**Comment by lanrete** [comment]
Thank you! I do notice now that this is posted in the wrong issue tracker.. my bad

I am still pretty new to elisp so please correct me if I am wrong, even if I put my configuration in an `(after! PACKAGE)` block, won't the code hook still over-writing the setting once it is triggered? but anyway changing it to `add-to-list` should definitely accommodate my case.

>  I think this was a typo
Yes this is a typo, nice catch.

Since this is in the wrong issue tracker and it is essentially resolved, I will close this issue

**Comment by hlissner** [comment]
> even if I put my configuration in an (after! PACKAGE) block, won't the code hook still over-writing the setting once it is triggered?

Actually, you're right. I've pushed a few updates for the lang/org module so that your `after!` blocks take precedence. So long as you put it in `~/.doom.d/config.el` (and not `~/.doom.d/init.el`), your config will overwrite Doom's defaults.
