### ISSUE TITLE
What fonts are used in the screenshots?

### ISSUE THREAD

**Issue by vityafx** [hlissner/emacs-doom-themes#299]
Hey there! Thank you for the themes! I would like to know, what fonts did you use for making the screenshots?

**Comment by hlissner** [comment]
I'm assuming you're referring to this screenshot (there are quite a few and not all of them are mine):

![image](https://user-images.githubusercontent.com/510883/61002825-bd538280-a362-11e9-9277-6deea685720d.png)

In which case, it's been a while since that screenshot, but iirc, the monospace font is either [Inconsolata](https://www.levien.com/type/myfonts/inconsolata.html) or [Input Mono Narrow](http://input.fontbureau.com/) and the sans-serif font in the treemacs sidebar is Input Sans (from the same bundle).

**Comment by vityafx** [comment]
What a coincidence, I have just installed them! Thank you :)

**Comment by arzg** [comment]
I know this issue is long-dead, but for anyone coming here from Google: after some closer inspection, the fonts in the image above appear to be [Fira Mono and Fira Sans](https://github.com/bBoxType/FiraSans) in code and the sidebar respectively.
