### ISSUE TITLE
Is there anyway to set a theme for just the doom bar?

### ISSUE THREAD

**Issue by brotatos** [hlissner/emacs-doom-themes#350]

**Comment by hlissner** [comment]
I'm assuming you mean [doom-modeline](https://www.emacswiki.org/emacs/CustomizingFaces). No, there is no way to set a theme only for the modeline. You will have to tweak it yourself with emacs' face API or the `custom-set-faces` macro:

```lisp
(custom-set-faces
 '(mode-line ((t (:background ,(doom-color 'blue)))))
 '(mode-line-emphasis ((t (:foreground ,(doom-color 'red)))))
 '(mode-line-buffer-id ((t (:background ,(doom-color 'bg)))))
 ...)
```

**Comment by pistach3** [comment]
Hi

Sorry to reopen this issue.
I was trying to change the color of my modeline by using the piece of code above

```
 (custom-set-faces
 '(mode-line ((t (:background ,(doom-color 'blue)))))
```

The problem is that I have an error on startup:
```
(wrong-type-argument stringp (, (doom-color (quote blue))))
```

I managed to make it work by using: 
```
(custom-set-faces
  '(mode-line ((t (:background "#a66d9b")))))
```

As I am not a Doom-Lisperer I don't quite understand the error around the doom-color.

Can you help me?

Thank you :)

**Comment by hlissner** [comment]
@pistach3 It is a quoting issue. You cannot interpolate values into a quoted list, but you can interpolate them into a _back_quoted list:

```diff
 (custom-set-faces
- '(mode-line ((t (:background ,(doom-color 'blue)))))
+ `(mode-line ((t (:background ,(doom-color 'blue)))))
```

**Comment by pistach3** [comment]
Thank you !
Have a nice day
