### ISSUE TITLE
Notes on Fairyfloss

### ISSUE THREAD

**Issue by Auralcat** [hlissner/emacs-doom-themes#351]
Hey everyone :D

I've read the [mention of the port of Fairyfloss that I've continued](https://github.com/hlissner/emacs-doom-themes/issues/287) just now. As a user of doom-themes, I'm glad that the theme made it to the collection. 🎉 

I'd like to share some notes about the porting process:
- The theme ended up being defined only for programming modes. I had to make some design decisions regarding org-mode and extra-modes like rainbow-parentheses, but I'm not proficient with colors and whatnot. So I've picked what felt right for me at the time and the modes I used most.
- The standard background color `#5a5475` shows a brighter hue in GUI Emacs than in other ports of the theme. I have no idea why it does that. Switching it to `#433c65` made it look closer to the original Sublime Text implementation.
- Kudos for adjusting the colors in Magit! ❤️ 
   I've read that [these faces aren't as easy to customize as the rest](https://magit.vc/manual/magit/Theming-Faces.html), and haven't tried to do it so far.

This is pretty much it. I'd like to hear more about how you approached the design decisions. :)

**Comment by ema2159** [comment]
I was the one that ported it! Mostly I probed VS Code version's colors and from there I tried to adjust the colors to some plugins or modes like Magit or Markdown which usually are the hardest to get. 
Overall I relied on doom-themes robustness which is pretty good and from there, receiving feedback was key to progressively improve the theme. I enjoy working on the theme and it's been one of the most liked from the package on recent times.
Regarding the hue problem, It's weird because the background looks the same (and it is the same because I probed it) on VS Code so I'm not really sure.

**Comment by ema2159** [comment]
@Auralcat shall I close this issue?

**Comment by Auralcat** [comment]
I guess so. I didn't have much time to look further into the theme right now :/ 

The main purpose here was to share what I've learned when porting the theme and exchange experiences.

**Comment by ema2159** [comment]
@Auralcat well that's pretty cool. It's pretty nice that so many people like this theme that much. I appreciate your review and I'm open to any suggestions.
I'll close the issue for now but if you find anything that you feel is worth mentiontioning write it right here, I'll be glad to help and fix any issue.
