### ISSUE TITLE
Remove bold setting from paren-face-*match

### ISSUE THREAD

**Issue by ThibautVerron** [hlissner/emacs-doom-themes#465]
Hi,

Some proportional fonts have different character width for bold and non-bold characters, causing text to move around when a face is applied or removed.

It is okay for content such as titles, but inconvenient for transient faces such as `paren-face-match`, `paren-face-mismatch` and `paren-face-no-match` (also used by smartparens).

Is it possible to remove the weight attribute for those faces?

Thanks!

**Comment by hlissner** [comment]
Faces can be modified with `custom-set-faces` (or `custom-set-faces!` if you use Doom Emacs):

```elisp
(custom-set-faces
  '(paren-face-match ((t (:weight normal))))
  '(paren-face-mismatch ((t (:weight normal))))
  '(paren-face-no-match ((t (:weight normal)))))

;; or for doom users:
(custom-set-faces!
  '((paren-face-match paren-face-mismatch paren-face-no-match)
    :weight normal))
```

O

**Comment by ThibautVerron** [comment]
Thanks for the quick reply! Yes I know how to do that, and it also requires re-setting the inherit for show-paren and smartparens faces.

But what is the rationale for having the weight attribute in the first place?

Also, it is tangential, but is it by design that show-paren faces (from `faces.el`) are inherited from mic-paren faces (melpa)? Shouldn't it be the opposite?

In practice, it doesn't seem to lead to problems on my system without mic-parens, but I don't understand why. Is it because doom-theme does some dark magic to hard-copy inherited attributes into the child faces?

Best wishes,

**Comment by hlissner** [comment]
> But what is the rationale for having the weight attribute in the first place?

To make the matched parens more distinct, particularly in lisps. More so for `rainbow-delimiters` users, where each paren is colored by depth, and so "red" isn't distinct enough.

This is generally fine for fixed pitch fonts, but I can see how it'd be annoying for variable pitch fonts. Still, my impression is monospaced text is a more common use-case in Emacs (to the dismay of those that use Emacs solely for org mode, I suspect), so I hesitate to change the default, especially when changing it is relatively simple.

> is it by design that show-paren faces (from faces.el) are inherited from mic-paren faces (melpa)? Shouldn't it be the opposite?

Only because the `mic-paren` faces come first in the file (they are alphabetized) and `&inherit`'s are read in one pass (i.e. in sequence).

> In practice, it doesn't seem to lead to problems on my system without mic-parens, but I don't understand why. Is it because doom-theme does some dark magic to hard-copy inherited attributes into the child faces?

You've guessed correctly. `&inherit` is indeed doom-themes specific, and magical. It exists to simplify the maintenance of several faces that serve the same purpose, where the ordinary `:inherit` will fail if the parent faces are never loaded.

Hope that helps!

**Comment by ThibautVerron** [comment]
Yes I see your point. I don't use rainbow-delimiters, but even without maybe I will feel the need to 
add :inverse-video to the faces.

> Still, my impression is monospaced text is a more common use-case in Emacs (to the dismay of those that use Emacs solely for org mode, I suspect)

You're probably right, but it also doesn't have to be exclusive. I personally use variable-pitch whenever I'm writing text (org, latex, emails, random txt files...) and fixed-pitch for everything else.

But I don't think that there is any way to specify different settings according to the pitch of the font, so the default makes sense.

I guess in the long run I should just find a proportional font not changing the width of bold characters, and with more white space than usual around parentheses...

> You've guessed correctly. &inherit is indeed doom-themes specific, and magical. It exists to simplify the maintenance of several faces that serve the same purpose, where the ordinary :inherit will fail if the parent faces are never loaded.

Thanks for the explanation!
