### ISSUE TITLE
Feature request: simple theme variables

### ISSUE THREAD

**Issue by jerbaroo** [hlissner/emacs-doom-themes#565]
It would be amazing if we could set a theme through a number of variables e.g. as below. Some simple layer that maps colours to a variety of other colour variables that Doom may use.

comment     
activeBorder
lineHighlight
container   
nonText     
tabDropBg   
bgLighter   
bgLight     
bgDark      
bgDarker    
selection   
menuHover

**Comment by hlissner** [comment]
This is being worked on as part of https://github.com/hlissner/emacs-doom-themes/issues/314 (as I rewrite our underlying framework in [emacs-doom-themer](https://github.com/hlissner/emacs-doom-themes/issues/427)). It introduces inheritance, so users would be able to easily create their own derived themes without having to add face support for every package under the sun.

Anyhow, since this is being addressed elsewhere (though the exact implementation details are still in the air) I will close this.

**Comment by jerbaroo** [comment]
Fantastic Henrik
