### ISSUE TITLE
there are no good themes with a really black background

### ISSUE THREAD

**Issue by vigilancetech-com** [hlissner/emacs-doom-themes#590]
## What happened?

I have eyesight problems and I find a theme that has a really black background with high contrast letters in pleasant colors works the best

## What did you expect to happen?

There to be at least one usable theme for me in doom-themes

## Steps to reproduce
1. load up doom themes
2. check them all
3. find out there are none
4.  the closest is manoj-dark but you can't see the buffer needs saving icon in the active buffer (and it's really not dark enough).
5. here are some suggestions for inclusion:

blackboard, calm forest, calmer forest, dark mint, dark krystal, distinguished, euphoria, evenhold, flatland black, flatui dark, grand shell theme, green screen theme, hemisu, hipster, hober, Ir Black Theme, jsc dark theme, klere, kosmos, late nite theme, lawrence, ld dark theme, lethe, matrix, midnight, minimal, modus vivendi, monochrome, nyx, oswald, pok wob, purple haze, quazi monochrome, renegade, retro green, retro orange, reverse, sexy monochrome, soothe, subdued, taming mr arneson, taylor, tomorrow night paradise, tty dark, ujelly, waher, wintermute,  

## System Information

I don't think any of this really matters

**Comment by ema2159** [comment]
You're right. I apologize for that. It has been a while since I or Henrik implemented or ported a theme ourselves and themes are included mostly by PR and we haven't received that many high contrast themes. I will try to see if there are any themes in the current PRs that suit your needs and if not I will try to implement one for you. There is one PR for the IR_black theme but it's not quite there yet.

**Comment by ema2159** [comment]
@vigilancetech-com now, IR Black has been merged! It is a start!

**Comment by hlissner** [comment]
I will close this issue since:

1. As mentioned, we have IR Black now, which satisfies the original request.
2. We have a few high contrast themes.
3. You can also trivially customize the background of a given them using the `custom-set-faces` macro.

   ```elisp
   (custom-set-faces! '(default ((t (:background "#000000")))))
   ```
4. "At least one usable theme for me" is too open ended and vague a request.

In any case, thanks for bringing it to our attention!
