### ISSUE TITLE
[Bug] Incorrect LaTeX preview 

### ISSUE THREAD

**Issue by Titikomba** [hlissner/emacs-doom-themes#610]
## What happened?
When rendering LaTeX, this unwanted background frame appears. 
![image](https://user-images.githubusercontent.com/56675361/120245470-94497d00-c26d-11eb-830a-83a2f525e625.png)
This screenshot has been taken with the doom-gruvbox theme, but this holds for all doom-xxx themes. 

## What did you expect to happen?
With non doom-xxx themes (here Wombat, included in doom),   everything is fine.
![image](https://user-images.githubusercontent.com/56675361/120245614-fbffc800-c26d-11eb-8ef9-e78cddf306b2.png) 

## Steps to reproduce
Here are the sentences of the screenshots. The last one is rendered within org-mode through C-c C-x C-l
```latex
First, I test $\frac{1}{\phi} = \phi - 1$.
Then, I test $\frac{1}{\phi} = \phi - 1$
Lastly, I test $\phi \simeq 1.618$
```

## System Information
+ Emacs version: 27.2
+ Emacs Distro: Doom Emacs
+ Operating System: Arch
+ Installed commit of doom-themes: d41435e

**Comment by hlissner** [comment]
Unfortunately this isn't something that can be fixed from our themes. The org package applies the `org-block` face indiscriminately to these latex blocks, I don't intend to change `org-block` simply for this, since I want src and example blocks to have a distinct background, but there is no way to target these inline latex snippet from our end; you'll have to request it of the org devs to either change the `org-src-font-lock-fontify-block` function to treat inline latex blocks specially, or to add another `org-latex` face (like they have with `org-quote`).

It _can_ be worked around from your end however, either:

1. Turn off `org-block`'s background (at the expense of src/example blocks):
    ```elisp
    (custom-set-faces `(org-block ((t (:background nil)))))
    ```
2. Don't have org natively highlight inline latex, in which case it'll use the `org-latex-and-related` face, which you can customize easily:
    ```elisp
    (setq org-highlight-latex-and-related '(latex))
    ```
3. Or force Org to use the `default` face for these inline blocks:
    ```elisp
    (add-to-list 'org-src-block-faces '("latex" default))
    ```
    (this will affect src blocks for latex too)

As this isn't something that we can address on our end, I will close this.

Hope that helps!

**Comment by Titikomba** [comment]
Thank you for quick answer and your amazing job on Doom ;)
Best,

**Comment by Titikomba** [comment]
For the sake of completeness,
```lisp
(setq org-highlight-latex-and-related '(latex))
```
is the even way to adress the problem, according to an org-mode maintainer ;)
