### ISSUE TITLE
Emacs Themes are messed up in terminal

### ISSUE THREAD

**Issue by ashkan-leo** [hlissner/emacs-doom-themes#684]
### What did you expect to happen?

When I set my theme when running emacs in a terminal, I see different and unexpected behavior compared to when running emacs GUI. The most notable is the dark-solarized theme which becomes blue when I run in my terminal. 

This is how dark solarized look like inside my terminal:
<img width="2056" alt="Screen Shot 2021-11-21 at 23 22 37" src="https://user-images.githubusercontent.com/10341965/142805352-071463a4-85a6-4a0b-9937-8bbaecb52f58.png">

### What actually happened?

When setting theme to dark solarized, it became blue.

### Steps to reproduce

1. run emacs in shell
2. set theme to be dark-solarized by` SPC m t`.
3. observe that emacs is blue  

### Package commit

b66aaf9e9f69ea724fa2038f7c532aa148abeb75 

### System Information

I see similar behavior in Nix OS 21.05 and Mac OS 11.

**Comment by hlissner** [comment]
Terminals are constrained to 256 colors, so we have a very limited color palette to work with. What you are seeing is the expected result. 

The only way to get better is to do one of the following:

1. Adopt a terminal that supports 24-bit color (e.g. alacritty, st, termite, etc) and [activate 24-bit color support for your teminal+Emacs](https://github.com/syl20bnr/spacemacs/wiki/Terminal).
2. Customize your terminal (E.g. via Xresources) so that all those 255 colors are approximated to solarized color palette (very cumbersome, might be easier with https://github.com/martenlienen/xresources-theme).
3. Or use another theme that happens to look better in a 256 color terminal.

As this is not an actionable bug, I will close this, but feel free to follow up here.

**Comment by Diablo-D3** [comment]
emacs supports 24 bit truecolor mode, you just have to make sure you have a terminfo for it, such as `xterm-direct`, `tmux-direct`, or (in my case) [`xterm-24bits`](https://github.com/Diablo-D3/dotfiles/raw/master/modules/bash/xterm-24bits) (goes in `~/.terminfo/x`) (due to some emulators not supporting the new tc syntax, just the old kind; `xterm-direct` is the new syntax). Set your `$TERM` to the appropriate one, and it should start working for you.
